server:
  port: 8081
spring:
  application:
    name: FPRO
    time_zone: GMT+7
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://ls-4858f5b1ba4c5b862804146ab97d20fce7e7f6c7.cjlmnrhfxrnx.ap-southeast-1.rds.amazonaws.com:3306/fpro
#    url: jdbc:mysql://localhost:3306/mikepro
    #url=jdbc:postgresql://192.168.2.100:5432/nagakawa_guarantee
    username: dbmasteruser
    password: $-_$0f2uX+z37fg3aXw_2pAs0unO%nkk
    hikari:
      auto-commit: false
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false
    #    properties:
#      hibernate.id.new_generator_mappings: true
#      hibernate.connection.provider_disables_autocommit: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.temp.use_jdbc_metadata_defaults: false
##      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
#      hibernate.cache.hazelcast.instance_name: nagakawa_guarantee
#      hibernate.cache.hazelcast.shutdown_on_session_factory_close: false
#      hibernate.cache.use_minimal_puts: true
#      hibernate.cache.hazelcast.use_lite_member: true
#      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 30
#      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.yandex.com
    port: 465
    username: tiemchung@evotek.vn
    password: tmcacannqrzkatgc
    protocol: smtp
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
  messages:
    encoding: 'UTF-8'
    use-code-as-default-message: true
    basename: i18n/labels
    cache-duration: 60    # 60 second,
  redis:
    host: localhost
    port: 6379
    password:
    embedded: true
    timeout: 10s

validation:
  password-regex: ^(?=.*[a-z])(?=.*[A-Z]).{8,}$ #password ít nh?t 8 ký t? , 1 ch? th??ng, 1 ch? hoa .. advance ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{8,}$
  username-regex: '^[a-zA-Z0-9]([._](?![._])|[a-zA-Z0-9]){1,72}[a-zA-Z0-9]$' #ky tu so + chu , ký t? (. _), do dai tu 3 den 75
  email-regex: '^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,35})$' #email không quá 100 ký t?
  phone-number-regex: '^((\\s){0,}((\\+84-?)|0))((9|8|7|3|5|4|2)[0-9]{8,9}(\\s){0,})$'
  coordinate-regex: '^(-?\d+(\.\d+)?),\s*(-?\d+(\.\d+)?)$'
  phone-number-min-length: 4
  phone-number-max-length: 11
  fullname-min-length: 2
  fullname-max-length: 200
  username-min-length: 3
  username-max-length: 75
  password-min-length: 8
  password-max-length: 50
  email-min-length: 4
  email-max-length: 100
  name-max-length: 255
  code-min-length: 2
  code-max-length: 50
  address-max-length: 255
  description-max-length: 255
  int-number-max-length: 10